project:
  type: website

website:
  title: "Master ISDD fiches"
  navbar:
    background: "#8a1538"
    foreground: "black"
    logo: "images/UniversiteParisCite_logo_horizontal_noir_RVB.png"
    left: 
      - text: "MDA"
        menu:
        - mda/mda.qmd
        - mda/pages/tp1.qmd
        - mda/pages/tp2.qmd
        - mda/pages/tp3.qmd
        - mda/pages/tp4.qmd
      - about.qmd
    tools:
      - icon: github
        href: https://github.com/MartinBaGar/Master_ISDD_fiches
        aria-label: GitHub
      - icon: envelope-at
        href: mailto:martin.bari-garnier@etu.u-paris.fr
        
  reader-mode: true

format:
  html:
    theme: 
      - custom.scss
    css: styles.css
    toc: true
    smooth-scroll: true

execute:
  freeze: auto

# Path to the image of ISDD
image: ../images/isdd_logo.png