project:
  type: website

website:
  title: "Master ISDD fiches"
  navbar:
    logo: "images/UniversiteParisCite_logo_horizontal_noir_RVB.png"
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      - custom.scss
    css: styles.css
    toc: true



