project:
  type: website

website:
  title: "Master_ISDD_fiches"
  navbar:
    logo: "images/UniversiteParisCite_logo_horizontal_couleur_RVB.png"
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



