project:
  type: website

website:
  title: "Master ISDD fiches"
  navbar:
    logo: "images/UniversiteParisCite_logo_horizontal_noir_RVB.png"
    left: 
      - text: "MDA"
        menu:
        - mda/mda.qmd
        - mda/a.qmd
        - mda/b.qmd
      - about.qmd
  reader-mode: true

format:
  html:
    theme: 
      - custom.scss
    css: styles.css
    toc: true
